version: '3.8'

volumes:
  postgres_data:
      driver: local

services:

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    restart: always
    ports:
     - "2181:2181"
    environment:
     - ALLOW_ANONYMOUS_LOGIN=yes
     
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    ports:
     - "9092:9092"
    restart: always
    depends_on:
     - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=LISTENER_MINAN://localhost:9092,LISTENER_MRM://kafka:29092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=LISTENER_MINAN:PLAINTEXT,LISTENER_MRM:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=LISTENER_MINAN://localhost:9092,LISTENER_MRM://kafka:29092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=LISTENER_MRM
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes


  configserver:
    build: ./configServer
    container_name: configserver
    image: config-server-image
    restart: always
    ports:
     - "8889:8888"
    volumes:
     - ./configServer:/app
    environment:
     - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/mhmmedinan/configServer
  
  discoveryserver:
    build: ./discoveryServer
    container_name: discoveryserver
    image: discovery-server-image
    restart: always
    ports:
     - "9001:9001"
    volumes:
     - ./discoveryServer:/app
    depends_on:
      - configserver

  apigateway:
    build: ./apigateway
    container_name: apigateway
    image: muhammedinan/api-gateway-image
    restart: always
    ports:
     - "9011:9011"
    volumes:
     - ./apigateway:/app
    depends_on:
     - discoveryserver
     - configserver
     - keycloak
    environment:
     - SPRING_PROFILES_ACTIVE=docker

  
  inventorydb: 
    container_name: inventorydb
    image: postgres
    restart: always
    ports:
     - "5437:5432"
    environment:
     - POSTGRES_USER=admin
     - POSTGRES_PASSWORD=12345

    volumes:
     - "./pg_data:/var/lib/postgresql/data"


  inventory-service:
   build: ./inventoryService
   container_name: inventory-service
   image: inventory-service
   restart: always
   volumes:
    - ./inventoryService:/app
   depends_on:
    - inventorydb
    - discoveryserver
    - kafka
    - configserver
   environment:
    - SPRING_PROFILES_ACTIVE=docker

  filterdb:
    container_name: filterdb
    image: mongo
    restart: always
    ports:
     - "27017:27017"
    volumes:
     - "/data/db/" 

  filter-service:
   build: ./filterService
   container_name: filter-service
   image: filter-service-api
   restart: always
   volumes:
     - ./filterService:/app
   depends_on:
     - configserver
     - discoveryserver
     - kafka
     - filterdb
   environment:
     - SPRING_PROFILES_ACTIVE=docker
  
  rentaldb: 
   container_name: rentaldb
   image: postgres
   restart: always
   ports:
     - "5436:5432"
   environment:
     - POSTGRES_USER=admin
     - POSTGRES_PASSWORD=12345

   volumes:
     - "./pg_data:/var/lib/postgresql/data"

  rental-service:
   build: ./rentalService
   container_name: rental-service
   image: rental-service
   restart: always
   volumes:
     - ./rentalService:/app
   depends_on:
     - rentaldb
     - discoveryserver
     - kafka
     - configserver
   environment:
     - SPRING_PROFILES_ACTIVE=docker

  paymentdb: 
    container_name: paymentdb
    image: postgres
    restart: always
    ports:
     - "5438:5432"
    environment:
     - POSTGRES_USER=admin
     - POSTGRES_PASSWORD=12345

    volumes:
     - "./pg_data:/var/lib/postgresql/data"

  payment-service:
   build: ./paymentService
   container_name: payment-service
   image: payment-service
   restart: always
   volumes:
     - ./paymentService:/app
   depends_on:
     - paymentdb
     - discoveryserver
     - kafka
     - configserver
   environment:
     - SPRING_PROFILES_ACTIVE=docker

  invoicedb: 
    container_name: invoicedb
    image: postgres
    restart: always
    ports:
     - "5439:5432"
    environment:
     - POSTGRES_USER=admin
     - POSTGRES_PASSWORD=12345

    volumes:
     - "./pg_data:/var/lib/postgresql/data"

  invoice-service:
   build: ./invoiceService
   container_name: invoice-service
   image: invoice-service
   restart: always
   volumes:
     - ./invoiceService:/app
   depends_on:
     - invoicedb
     - discoveryserver
     - kafka
     - configserver
   environment:
     - SPRING_PROFILES_ACTIVE=docker

  keycloak_postgres: 
    container_name: keycloak_postgres
    image: postgres
    restart: always
    ports:
     - "5435:5432"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
     - "postgres_data:/var/lib/postgresql/data"

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:legacy
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak_postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - keycloak_postgres
  
